openapi: 3.0.0
info:
  title: OTUS Highload Architect
  version: 1.2.0
servers:
- url: /
paths:
  /counter/{counter_id}:
    get:
      parameters:
      - explode: false
        in: path
        name: counter_id
        required: true
        schema:
          $ref: '#/components/schemas/CounterId'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_counter__counter_id__get_200_response'
          description: Успешно отправлено сообщение
        "400":
          description: Невалидные данные ввода
        "401":
          description: Неавторизованный доступ
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_counter__counter_id__get_500_response'
          description: Ошибка сервера
          headers:
            Retry-After:
              description: "Время, через которое еще раз нужно сделать запрос"
              explode: false
              required: false
              schema:
                type: integer
              style: simple
        "503":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_counter__counter_id__get_500_response'
          description: Ошибка сервера
          headers:
            Retry-After:
              description: "Время, через которое еще раз нужно сделать запрос"
              explode: false
              required: false
              schema:
                type: integer
              style: simple
      security:
      - bearerAuth: []
components:
  responses:
    "400":
      description: Невалидные данные ввода
    "401":
      description: Неавторизованный доступ
    "5xx":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/_counter__counter_id__get_500_response'
      description: Ошибка сервера
      headers:
        Retry-After:
          description: "Время, через которое еще раз нужно сделать запрос"
          explode: false
          required: false
          schema:
            type: integer
          style: simple
  schemas:
    CounterId:
      type: string
    CounterValue:
      format: int64
      type: integer
    _counter__counter_id__get_200_response:
      example:
        value: 0
      properties:
        value:
          format: int64
          type: integer
      required:
      - value
      type: object
    _counter__counter_id__get_500_response:
      properties:
        message:
          description: Описание ошибки
          type: string
        request_id:
          description: Идентификатор запроса. Предназначен для более быстрого поиска
            проблем.
          type: string
        code:
          description: Код ошибки. Предназначен для классификации проблем и более
            быстрого решения проблем.
          type: integer
      required:
      - message
      type: object
  securitySchemes:
    bearerAuth:
      description: "Авторизация по токену, который был получен в методе /login"
      scheme: bearer
      type: http
