version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_DATABASE: 'db'
      DB_USER: 'user'
      DB_PASSWORD: 'password'
      DB_ADDRESS: 'db:3306'
      CACHE_ENABLED: ${CACHE_ENABLED:-true}
      DEBUG: ${DEBUG:-false}
      CACHE_FEED_LIMIT: '1000'
      ASYNCAPI_ENABLED: 'true'
      RMQ_ADDRESS: 'rabbitmq:5672'
      DIALOG_MICROSERVICE_ENABLED: 'true'
      DIALOG_ADDRESS: 'dialog:8081'
      OTEL_SERVICE_NAME: 'app'
      OTEL_EXPORTER_JAEGER_ENDPOINT: 'http://jaeger:14268/api/traces'
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - '8080:8080'
    expose:
      - '8080'
  dialog:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APPLICATION: dialog
    environment:
      DEBUG: ${DEBUG:-false}
      TARANTOOL_ADDRESS: 'http://tarantool_dialog:3380'
      COUNTER_ADDRESS: 'counter:8081'
      OTEL_SERVICE_NAME: 'dialog'
      OTEL_EXPORTER_JAEGER_ENDPOINT: 'http://jaeger:14268/api/traces'
    depends_on:
      tarantool_dialog:
        condition: service_started
    ports:
      - '8180:8080'
      - '8081:8081'
    expose:
      - '8081'
      - '8180'
  counter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APPLICATION: counter
    environment:
      DEBUG: ${DEBUG:-false}
      TARANTOOL_ADDRESS: 'tarantool_counter:3301'
      TARANTOOL_USERNAME: 'storage'
      TARANTOOL_PASSWORD: 'passw0rd'
      OTEL_SERVICE_NAME: 'counter'
      OTEL_EXPORTER_JAEGER_ENDPOINT: 'http://jaeger:14268/api/traces'
    depends_on:
      tarantool_counter:
        condition: service_started
    ports:
      - '8182:8080'
      - '8082:8081'
    expose:
      - '8082'
      - '8182'
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ${PWD}/db/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ${PWD}/db/single/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    expose:
      - '5672'
  tarantool_dialog:
    image: tarantool/tarantool:2.11
    command: tarantool /opt/tarantool/app.lua
    ports:
      - '3380:3380'
    expose:
      - '3380'
    volumes:
      - tarantool_dialog-db:/var/lib/tarantool
      - ${PWD}/tarantool/dialog:/opt/tarantool
  tarantool_counter:
    image: tarantool/tarantool:2.11
    command: tarantool /opt/tarantool/app.lua
    ports:
      - '3301:3301'
    expose:
      - '3301'
    volumes:
      - tarantool_counter-db:/var/lib/tarantool
      - ${PWD}/tarantool/counter:/opt/tarantool
  jaeger:
    image: jaegertracing/all-in-one:1.6
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
volumes:
  my-db:
  tarantool_dialog-db:
  tarantool_counter-db:
