version: '3.3'
services:
  app:
    environment:
      DEBUG: "true"
    deploy:
      replicas: 2
    ports: []
    expose: []
  app_proxy:
    image: nginx:1.25.2-alpine
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    expose:
      - "8080"
  db:
    image: haproxy:2.8
    volumes:
      - "${PWD}/db/ha/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    ports:
      - "3306:3306"
      - "9999:9999"
    depends_on:
      - db_init
  db_init:
    image: mysql:8.0
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    entrypoint: [ "bash", "-c", "./replication_init.sh || exit 1; sleep infinity"]
    volumes:
      - ${PWD}/db/ha/replication_init.sh:/replication_init.sh
    depends_on:
      - db_1
      - db_2
  db_1:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - my-db_1:/var/lib/mysql
      - ${PWD}/db/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ${PWD}/db/ha/mysql_1.cnf:/etc/mysql/conf.d/mysql.cnf
  db_2:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    expose:
      - '3308'
    volumes:
      - my-db_2:/var/lib/mysql
      - ${PWD}/db/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ${PWD}/db/ha/mysql_2.cnf:/etc/mysql/conf.d/mysql.cnf
volumes:
  my-db_1:
  my-db_2:
