version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_DATABASE: 'db'
      DB_USER: 'user'
      DB_PASSWORD: 'password'
      DB_ADDRESS: 'db:3306'
      CACHE_ENABLED: ${CACHE_ENABLED:-true}
      DEBUG: 'false'
      CACHE_FEED_LIMIT: '1000'
      ASYNCAPI_ENABLED: 'true'
      RMQ_ADDRESS: 'rabbitmq:5672'
      DIALOG_MICROSERVICE_ENABLED: 'true'
      DIALOG_ADDRESS: 'http://dialog:8080'
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - '8080:8080'
    expose:
      - '8080'
  dialog:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APPLICATION: dialog
    environment:
      DEBUG: 'false'
      TARANTOOL_ADDRESS: 'http://tarantool:3380'
    depends_on:
      tarantool:
        condition: service_started
    ports:
      - '8081:8080'
    expose:
      - '8081'
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ${PWD}/db/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ${PWD}/db/single/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    expose:
      - '5672'
  tarantool:
    image: tarantool/tarantool:2.3.1
    command: tarantool /opt/tarantool/app.lua
    ports:
      - '3380:3380'
    expose:
      - '3380'
    volumes:
      - tarantool-db:/var/lib/tarantool
      - ${PWD}/tarantool/src:/opt/tarantool
volumes:
  my-db:
  tarantool-db:
