version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_DATABASE: 'db'
      DB_USER: 'user'
      DB_PASSWORD: 'password'
      DB_ADDRESS: 'db:3306'
    depends_on:
      - db
    ports:
      - '8080:8080'
    expose:
      - '8080'
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ${PWD}/db:/docker-entrypoint-initdb.d
volumes:
  my-db:
