openapi: 3.0.0
info:
  title: OTUS Highload Architect
  version: 1.0.0
servers:
- url: /
paths:
  /login:
    post:
      description: Упрощенный процесс аутентификации путем передачи идентификатор
        пользователя и получения токена для дальнейшего прохождения авторизации
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_login_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_login_post_200_response'
          description: Успешная аутентификация
        "400":
          description: Невалидные данные
        "404":
          description: Пользователь не найден
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_login_post_500_response'
          description: Ошибка сервера
          headers:
            Retry-After:
              description: "Время, через которое еще раз нужно сделать запрос"
              explode: false
              required: false
              schema:
                type: integer
              style: simple
        "503":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_login_post_500_response'
          description: Ошибка сервера
          headers:
            Retry-After:
              description: "Время, через которое еще раз нужно сделать запрос"
              explode: false
              required: false
              schema:
                type: integer
              style: simple
  /user/register:
    post:
      description: Регистрация нового пользователя
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_user_register_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_user_register_post_200_response'
          description: Успешная регистрация
        "400":
          description: Невалидные данные
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_login_post_500_response'
          description: Ошибка сервера
          headers:
            Retry-After:
              description: "Время, через которое еще раз нужно сделать запрос"
              explode: false
              required: false
              schema:
                type: integer
              style: simple
        "503":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_login_post_500_response'
          description: Ошибка сервера
          headers:
            Retry-After:
              description: "Время, через которое еще раз нужно сделать запрос"
              explode: false
              required: false
              schema:
                type: integer
              style: simple
  /user/get/{id}:
    get:
      description: Получение анкеты пользователя
      parameters:
      - description: Идентификатор пользователя
        explode: false
        in: path
        name: id
        required: true
        schema:
          description: Идентификатор пользователя
          example: e4d2e6b0-cde2-42c5-aac3-0b8316f21e58
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: Успешное получение анкеты пользователя
        "400":
          description: Невалидные данные
        "404":
          description: Анкета не найдена
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_login_post_500_response'
          description: Ошибка сервера
          headers:
            Retry-After:
              description: "Время, через которое еще раз нужно сделать запрос"
              explode: false
              required: false
              schema:
                type: integer
              style: simple
        "503":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_login_post_500_response'
          description: Ошибка сервера
          headers:
            Retry-After:
              description: "Время, через которое еще раз нужно сделать запрос"
              explode: false
              required: false
              schema:
                type: integer
              style: simple
  /user/search:
    get:
      description: Поиск анкет
      parameters:
      - description: Условие поиска по имени
        explode: true
        in: query
        name: first_name
        required: true
        schema:
          description: Часть имени для поиска
          example: Конст
          type: string
        style: form
      - description: Условие поиска по фамилии
        explode: true
        in: query
        name: last_name
        required: true
        schema:
          description: Часть фамилии для поиска
          example: Оси
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/User'
                type: array
          description: Успешные поиск пользователя
        "400":
          description: Невалидные данные
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_login_post_500_response'
          description: Ошибка сервера
          headers:
            Retry-After:
              description: "Время, через которое еще раз нужно сделать запрос"
              explode: false
              required: false
              schema:
                type: integer
              style: simple
        "503":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_login_post_500_response'
          description: Ошибка сервера
          headers:
            Retry-After:
              description: "Время, через которое еще раз нужно сделать запрос"
              explode: false
              required: false
              schema:
                type: integer
              style: simple
components:
  responses:
    "5xx":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/_login_post_500_response'
      description: Ошибка сервера
      headers:
        Retry-After:
          description: "Время, через которое еще раз нужно сделать запрос"
          explode: false
          required: false
          schema:
            type: integer
          style: simple
  schemas:
    User:
      example:
        city: Москва
        second_name: Фамилия
        id: id
        biography: "Хобби, интересы и т.п."
        first_name: Имя
        age: 18
      properties:
        id:
          description: Идентификатор пользователя
          type: string
        first_name:
          description: Имя
          example: Имя
          type: string
        second_name:
          description: Фамилия
          example: Фамилия
          type: string
        age:
          description: Возраст
          example: 18
          type: integer
        biography:
          description: Интересы
          example: "Хобби, интересы и т.п."
          type: string
        city:
          description: Город
          example: Москва
          type: string
      type: object
    _login_post_request:
      properties:
        id:
          example: "234"
          type: string
        password:
          example: Секретная строка
          type: string
      type: object
    _login_post_200_response:
      example:
        token: e4d2e6b0-cde2-42c5-aac3-0b8316f21e58
      properties:
        token:
          example: e4d2e6b0-cde2-42c5-aac3-0b8316f21e58
          type: string
      type: object
    _login_post_500_response:
      properties:
        message:
          description: Описание ошибки
          type: string
        request_id:
          description: Идентификатор запроса. Предназначен для более быстрого поиска
            проблем.
          type: string
        code:
          description: Код ошибки. Предназначен для классификации проблем и более
            быстрого решения проблем.
          type: integer
      required:
      - message
      type: object
    _user_register_post_request:
      properties:
        first_name:
          example: Имя
          type: string
        second_name:
          example: Фамилия
          type: string
        age:
          example: 18
          type: integer
        biography:
          example: "Хобби, интересы и т.п."
          type: string
        city:
          example: Москва
          type: string
        password:
          example: Секретная строка
          type: string
      type: object
    _user_register_post_200_response:
      example:
        user_id: e4d2e6b0-cde2-42c5-aac3-0b8316f21e58
      properties:
        user_id:
          example: e4d2e6b0-cde2-42c5-aac3-0b8316f21e58
          type: string
      type: object
